### ISSUE TITLE
thesis code

### ISSUE THREAD

**Issue by bartengine27** [wilrop/Import-CGN#1]
Hi,

  Did you publish the source code of your thesis?

Thanks,
Bart

**Comment by wilrop** [comment]
Hi I'm very sorry for answering this late, I never actually saw this issue!

This is all of the source code needed for preprocessing the data. To train the actual models, I used the DeepSpeech engine together with a language model I made myself. So in essence, if you have the code from this repo, you mostly have everything you need.
